// Guided lessons use different examples from the battle tasks.
const lessons={};
function lesson(id,title,idea,use,code,steps,question,options,answer,explanation){lessons[id]={title,idea,use,code,steps,question,options,answer,explanation};}
lesson('assign','Give information a name','A variable is a name that remembers a value. Think of a labeled treasure box: coins is the label, and 12 is what is inside.','Write name = value. A whole number like 12 is called an integer. Python follows your instructions from top to bottom. print(name) shows the stored value.', 'coins = 12\nprint(coins)', ['coins = 12 stores the number 12 under the name coins.','print(coins) looks up coins and shows 12. Try changing 12 and running again.'], 'What does gems = 4 do?', ['Stores 4 under the name gems','Checks whether gems equals 4','Prints the word gems'],0,'The single = assigns a value to a name. It does not print or compare.');
lesson('update','Variables can change','Your hero does not keep the same HP forever. A new assignment replaces the old value.','Use a name on the right to read its old value, calculate something, and store the new value on the left.', 'hp = 70\nhp = hp - 5\nprint(hp)', ['hp starts at 70.','Read the old hp: 70 - 5 is 65. Store 65 back in hp.','print displays the new value: 65.'], 'After stars = 3 then stars = stars + 2, what is stars?', ['3','5','2'],1,'Read the old value first: 3 + 2 = 5. The assignment saves 5.');
lesson('strings','Words need quotation marks','Numbers and text are different kinds of values. Text is called a string. Quotation marks tell Python where the text starts and ends.','Use matching single or double quotes. Names without quotes are treated as variable names. Text is case-sensitive.', 'pet = "Nova"\nprint(pet)', ['"Nova" is text because it is inside quotes.','pet remembers that text. print(pet) shows Nova, without the quotes.'], 'Which line stores the text Luna?', ['pet = Luna','pet = "Luna"','pet == "Luna"'],1,'Quotes make Luna a string. Without them, Python looks for a variable named Luna.');
lesson('print','Show what your program knows','A program can store a value quietly. print() lets you see it on the screen.','Put text in quotes, or a variable name, inside the parentheses. Python uses # for a comment that it ignores.', 'score = 6\n# Show the current score\nprint(score)', ['Store 6 in score.','The line starting with # is a note, not an instruction.','print(score) displays the value 6.'], 'Which line displays the value in hp?', ['print("hp")','hp = print','print(hp)'],2,'print(hp) reads the variable. print("hp") displays the two letters hp.');
lesson('add','Calculate with variables','Python can do game math: add bonus damage, subtract a hit, or multiply rewards.','+ adds numbers, - subtracts, and * multiplies. Store a calculation in a variable so you can use it later.', 'power = 4\nboost = 2\ntotal = power + boost\nprint(total)', ['power remembers 4 and boost remembers 2.','Add 4 + 2 and store 6 in total.','Display 6. Try changing boost to 5.'], 'If power = 5 and boost = 3, what is power + boost?', ['8','53','2'],0,'Both values are numbers, so + adds them: 5 + 3 = 8.');
lesson('aug','A shortcut for changing a value','Collecting coins adds to your existing total. += is a shorter way to write that update.','coins += 3 means coins = coins + 3. -= subtracts from an existing value in the same way.', 'coins = 10\ncoins += 4\nprint(coins)', ['Start with 10 coins.','+= 4 adds four to the old total and stores 14.','Print 14. Try changing += to -=.'], 'Which line means hp = hp - 6?', ['hp = -6','hp -= 6','hp == 6'],1,'hp -= 6 subtracts six from the current hp. hp = -6 would replace it with negative six.');
lesson('division','Whole groups and leftovers','Imagine sharing 11 gems among 3 heroes. // counts complete gems per hero; % counts what is left over.','/ performs division, // gives the rounded-down whole quotient, and % gives the remainder. These examples use positive numbers.', 'print(11 // 3)\nprint(11 % 3)', ['Three groups of 3 use 9 gems. The whole quotient is 3.','11 - 9 leaves 2 gems. The remainder is 2.'], 'What is 8 % 3?', ['2','3','8'],0,'Two groups of 3 use 6. There are 2 left over.');
lesson('boolean','True or False','A Boolean is a value with only two possibilities: True and False. It is useful for things like whether a shield is active.','Python spells these with capital first letters. They are values, so you do not put them in quotes.', 'shield = True\nprint(shield)', ['Store the Boolean True in shield.','Print True. You can change True to False and run again.'], 'Which one is a Boolean value?', ['"True"','true','True'],2,'True is Python\'s Boolean. "True" is text, and lowercase true is treated as a name.');
lesson('join','Join pieces of text','The + symbol can also join strings. Both sides need to be text.','To combine a word and a name, join strings with +. str(number) converts a number to text when needed.', 'name = "Nova"\nprint("Hi " + name)', ['name stores Nova.','Join "Hi " and "Nova". The space inside the first string separates the words.'], 'What does "Code" + "Quest" make?', ['CodeQuest','Code Quest','An error'],0,'Joining strings does not add a space automatically.');
lesson('if','Let your program choose','A condition is a question with a True or False answer. if runs its block only when the condition is True.','Put a colon after the condition. Indent the instructions that belong to it by four spaces.', 'hp = 15\nif hp < 20:\n    print("Use a potion")', ['Store 15 in hp.','15 < 20 is True.','The indented print runs. Change hp to 30: that print will not run.'], 'When does the indented block after if run?', ['Always','Only when the condition is True','Only when it is False'],1,'if checks the condition before running its indented instructions.');
lesson('else','Choose between two paths','An else block is the other path: it runs when the if condition is False.','else ends with a colon too. It lines up with if; its instructions are indented.', 'coins = 4\nif coins >= 6:\n    print("Buy shield")\nelse:\n    print("Save coins")', ['coins is 4.','4 >= 6 is False, so skip the first print.','Take the else path and print Save coins. Try coins = 8.'], 'If the if condition is False, which block runs?', ['Both blocks','The if block','The else block'],2,'Only one of these two paths runs: if for True, else for False.');
lesson('compare','Compare values','Comparisons produce True or False. They let the game ask whether you have enough coins or whether an enemy is defeated.','== means equal, != means different, > means greater, < means smaller, and >= or <= include equality. A single = stores a value.', 'coins = 6\nprint(coins >= 6)\nprint(coins == 0)\nprint(coins != 0)', ['Store 6 in coins.','6 >= 6 is True because at least includes equal.','6 == 0 is False; 6 != 0 is True.'], 'Which checks whether hp equals zero?', ['hp = 0','hp == 0','hp += 0'],1,'Two equals signs compare values. One equals sign assigns a value.');
lesson('logic','Combine conditions','Sometimes one check is not enough. Healing might require low HP AND an available potion.','and needs both conditions to be True. or needs at least one. not reverses True and False.', 'hp = 12\npotions = 1\nprint(hp < 20 and potions > 0)\nprint(False or True)\nprint(not True)', ['Both hp < 20 and potions > 0 are True, so and gives True.','or gives True when either side is True.','not True becomes False.'], 'True and False gives what?', ['True','False','None'],1,'and requires both sides. One False side makes the result False.');
lesson('elif','Choose among several paths','An enemy can be strong, medium, or weak. elif adds another condition after an if.','Python tests from top to bottom and runs the first matching block. Put the most demanding condition first.', 'power = 7\nif power >= 10:\n    print("strong")\nelif power >= 5:\n    print("medium")\nelse:\n    print("weak")', ['7 >= 10 is False.','7 >= 5 is True, so print medium.','The else block is skipped because a condition already matched.'], 'If the first if is True, does Python also run a matching elif?', ['Yes','Only on Tuesdays','No'],2,'An if/elif/else chain chooses only the first matching path.');
lesson('list','Pack several items together','A list holds several values in order, like a backpack. Square brackets surround the list, and commas separate items.','Give the list a name. Text items still need quotes. len(list) counts how many items it holds.', 'bag = ["map", "rope", "apple"]\nprint(bag)\nprint(len(bag))', ['Make a three-item list and store it in bag.','Printing bag shows the list.','len(bag) is 3 because there are three items.'], 'Which creates a list of two numbers?', ['bag = (2 + 3)','bag = [2, 3]','bag = "2, 3"'],1,'Square brackets and a comma create a list.');
lesson('index','Pick an item by its position','Python counts list positions from zero. The first item is at index 0, the second at index 1.','Read list[index] to get an item. Index -1 is a handy way to read the last item.', 'bag = ["map", "rope", "apple"]\nprint(bag[0])\nprint(bag[1])\nprint(bag[-1])', ['The positions are 0: map, 1: rope, 2: apple.','bag[0] prints map; bag[1] prints rope.','bag[-1] prints apple, the last item.'], 'What index selects the second item?', ['2','1','0'],1,'Counting starts at 0, so the second item has index 1.');
lesson('append','Add something to your backpack','Lists can grow. append() adds a single new item to the end.','Write list_name.append(value). It changes the list directly; do not assign the result back to your list.', 'bag = ["map", "rope"]\nbag.append("apple")\nprint(bag)', ['Start with two items.','append adds apple after rope.','Print the updated three-item list.'], 'Where does append put the new item?', ['At the end','At the beginning','At index 0'],0,'append adds one item after the existing last item.');
lesson('listchange','Change or remove an item','A list is editable. You can replace one position or remove an item by its value.','list[index] = value replaces one item. list.remove(value) removes the first matching value; it raises an error if that value is absent.', 'bag = ["map", "old rope", "apple"]\nbag[1] = "new rope"\nbag.remove("apple")\nprint(bag)', ['Index 1 is old rope. Replace it with new rope.','remove finds apple and takes it out.','The list now holds map and new rope.'], 'Which replaces the first item in bag?', ['bag[1] = "key"','bag[0] = "key"','bag.append("key")'],1,'Index 0 is the first position. append would add an extra item instead.');
lesson('slice','Take a section of a list','A slice copies a section of a list, without removing the original items.','list[start:stop] includes start and stops just before stop. The stop position is excluded.', 'numbers = [10, 20, 30, 40]\nprint(numbers[1:3])', ['Index 1 contains 20.','Take positions 1 and 2, stopping before position 3.','The result is [20, 30].'], 'Which positions does items[0:2] include?', ['0 and 1','0, 1, and 2','Only 2'],0,'The stop is excluded, so positions 0 and 1 are included.');
lesson('membership','Is that item in the bag?','The in operator asks whether a collection contains a value. It returns a Boolean.','For lists, in checks items. For dictionaries, it checks keys.', 'bag = ["map", "rope"]\nprint("rope" in bag)\nprint("sword" in bag)', ['rope is an item in bag, so the first result is True.','sword is absent, so the second result is False.'], '"key" in ["map", "key"] returns what?', ['"key"','True','2'],1,'in answers a yes/no question with True or False.');
lesson('sum','Add a collection of numbers','sum() adds all the numbers in a collection. It is useful for total treasure or total damage.','Store sum(numbers) in a variable, or print it directly. An empty list has a sum of 0.', 'hits = [2, 4, 3]\ntotal = sum(hits)\nprint(total)', ['hits contains three numbers.','Add 2 + 4 + 3 and store 9 in total.','Print 9. Add another number to hits and run again.'], 'What is sum([1, 3, 2])?', ['6','3','[1, 3, 2]'],0,'sum adds the values: 1 + 3 + 2 = 6.');
lesson('for','Repeat for each item','A for loop visits each item in a collection. Think of checking every item in your backpack.','for item in collection: introduces a temporary name for the current item. Indent the work you want to repeat.', 'bag = ["map", "rope"]\nfor item in bag:\n    print(item)', ['The first item is map, so item becomes map and the print runs.','Next item becomes rope and the same print runs again.','The loop ends when there are no items left.'], 'How many times does a loop over [2, 4, 6] run?', ['2','6','3'],2,'It runs once for each of the three items.');
lesson('range','Count a set number of times','range() supplies a sequence of numbers for a loop. Its stop number is never included.','range(3) gives 0, 1, 2. range(start, stop, step) can start elsewhere or jump by a step.', 'for n in range(1, 6, 2):\n    print(n)', ['Start at 1 and print it.','Step by 2: print 3, then 5.','Stop before 6. The output is 1, 3, 5 on separate lines.'], 'Which values come from range(3)?', ['1, 2, 3','0, 1, 2','0, 1, 2, 3'],1,'With one argument, range starts at zero and excludes the stop.');
lesson('accumulate','Build a total one step at a time','A loop can collect a running total. Start with zero, then add each number.','Create total before the loop. Put the update inside the loop and the final print after it.', 'hits = [2, 5, 1]\ntotal = 0\nfor hit in hits:\n    total += hit\nprint(total)', ['Start total at 0.','The loop adds 2, then 5, then 1. The running totals are 2, 7, 8.','After the loop, print 8.'], 'Why put total = 0 before the loop?', ['To keep the running total instead of resetting it each time','To print every number','To skip the first item'],0,'Resetting inside the loop would lose the earlier additions.');
lesson('while','Repeat until a condition changes','A while loop repeats as long as its condition is True. It is good for a countdown.','Change something inside the loop so the condition eventually becomes False. Otherwise the loop may never stop.', 'count = 3\nwhile count > 0:\n    print(count)\n    count -= 1', ['Start with count = 3. Print 3 and reduce it to 2.','Repeat for 2, then 1.','When count becomes 0, count > 0 is False. Stop.'], 'What happens if we forget count -= 1 here?', ['It stops after one run','count becomes 0 automatically','It keeps repeating because count stays 3'],2,'The condition never changes, so the loop would continue. The game stops code that runs too long.');
lesson('loopcontrol','Stop or skip in a loop','break leaves the whole loop. continue skips the rest of this one turn and moves to the next item.','Use an if inside a loop to decide when to stop or skip.', 'for n in range(4):\n    if n == 1:\n        continue\n    if n == 3:\n        break\n    print(n)', ['n = 0 prints 0.','n = 1 uses continue, so skip its print.','n = 2 prints 2. n = 3 uses break and ends the loop.'], 'Which command stops the entire loop?', ['continue','break','print'],1,'break exits the loop; continue moves on to its next turn.');
lesson('filter','Keep only the items you want','You can combine a list, a loop, and an if to collect matching items.','Start an empty list. Visit each value, check it, and append it only if it matches.', 'powers = [3, 8, 2, 10]\nstrong = []\nfor power in powers:\n    if power > 5:\n        strong.append(power)\nprint(strong)', ['Start strong as an empty list.','3 and 2 do not pass power > 5. Skip them.','8 and 10 pass, so append them. Print [8, 10].'], 'Which values pass n > 4 in [2, 5, 4, 7]?', ['[5, 7]','[4, 5, 7]','[2, 4]'],0,'Greater than excludes 4 itself. Only 5 and 7 qualify.');
lesson('function','Build a reusable move','A function is a named set of instructions. Defining it is like teaching your hero a move; calling it performs the move.','Use def name(parameters): with an indented body. Parameters receive the values you pass when calling.', 'def triple(number):\n    return number * 3\nprint(triple(4))', ['def teaches Python what triple does; it does not run the body yet.','triple(4) sets number to 4 inside the function.','return sends back 12, which print displays.'], 'Which calls a function named heal with 5?', ['def heal(5):','heal(5)','heal = 5'],1,'Parentheses after the function name call it with the supplied argument.');
lesson('return','Send a result back','return gives a value back to whoever called the function. It also ends that function call.','Calculating a value alone does not return it. print shows a value on screen; return makes it available to other code.', 'def square(n):\n    return n * n\nanswer = square(3)\nprint(answer)', ['square(3) calculates 3 * 3.','return sends 9 back and ends the call.','Store 9 in answer, then print it.'], 'Which sends a computed value back to the caller?', ['print','return','def'],1,'return sends the result back. print only displays it.');
lesson('parameters','Give your move ingredients','Parameters are the names inside a function. Arguments are the values you supply when calling it.','Match arguments to parameters in order. A function can take more than one input.', 'def heal(hp, amount):\n    return hp + amount\nprint(heal(30, 7))', ['30 becomes hp and 7 becomes amount.','Add them and return 37.','print displays the returned value.'], 'In heal(20, 5), what value does amount receive?', ['20','25','5'],2,'The second argument goes into the second parameter, amount.');
lesson('nested','A move inside another move','One function call can supply a value to another. Work from the inside out.','Finish the inner call, then use its result as the argument for the outer call.', 'def boost(n):\n    return n + 3\nprint(boost(boost(2)))', ['The inner boost(2) returns 5.','The outer boost(5) returns 8.','print shows 8.'], 'If boost adds 3, what is boost(boost(1))?', ['4','7','3'],1,'Inner: 1 + 3 = 4. Outer: 4 + 3 = 7.');
lesson('defaults','Choose a default input','A default parameter lets someone call a function without supplying that value.','Put parameter=value in the definition. An argument in the call replaces that default.', 'def greet(name="friend"):\n    return "Hello " + name\nprint(greet())\nprint(greet("Nova"))', ['No argument: name uses the default friend.','greet() returns Hello friend.','Supplying Nova overrides the default and returns Hello Nova.'], 'What name is used by greet() in this example?', ['Nova','friend','name'],1,'An omitted argument uses the default specified in the definition.');
lesson('scope','Local names stay inside a move','A parameter is a local name inside a function. Reassigning a number parameter does not replace a name outside the function.','Return the new value and assign it outside if you want to keep the change.', 'def boost(n):\n    n = n + 3\n    return n\nhp = 10\nnew_hp = boost(hp)\nprint(hp)\nprint(new_hp)', ['hp is 10 outside the function. Inside, n starts at 10 and becomes 13.','Return 13 and store it in new_hp.','hp is still 10; new_hp is 13.'], 'Does assigning n = 99 inside this function replace outside hp?', ['No','Yes','Only if n is printed'],0,'n is a local name. Return a value and assign hp = boost(hp) to update hp.');
lesson('clamp','Keep a number in a safe range','Game HP should not go below zero or above its maximum. min and max help keep values within limits.','max(0, value) prevents negatives. min(100, value) prevents values above 100.', 'hp = 8\nhp = max(0, hp - 20)\nprint(hp)\nprint(min(100, 95 + 10))', ['8 - 20 is -12. max picks 0 instead.','Print 0: HP cannot go negative.','95 + 10 is 105. min picks 100 to cap healing.'], 'What is max(0, -4)?', ['-4','4','0'],2,'max chooses the larger number. Zero is larger than negative four.');
lesson('dict','Give each value a useful label','A dictionary connects keys to values. A hero record might connect "name" to "Nova" and "hp" to 80.','Use curly braces, key: value pairs, and commas. Look up a value with dictionary[key]. Keys are often strings.', 'hero = {"name": "Nova", "hp": 80}\nprint(hero["name"])\nprint(hero["hp"])', ['Create two key/value pairs.','The name key gives Nova.','The hp key gives 80. Keys identify values instead of positions.'], 'Which reads the hp value from hero?', ['hero[0]','hero["hp"]','hero.hp'],1,'Dictionary lookup uses the key inside square brackets.');
lesson('dictchange','Update a hero record','Dictionary values can change, and you can add or delete keys.','hero["hp"] = value replaces that value. Assigning a new key adds it. del hero["key"] removes that key.', 'hero = {"hp": 50, "curse": True}\nhero["hp"] += 5\nhero["armor"] = 2\ndel hero["curse"]\nprint(hero)', ['Increase hp from 50 to 55.','Add a new armor key with value 2.','Delete curse. The remaining keys are hp and armor.'], 'What does hero["armor"] = 3 do if armor is absent?', ['Raises an error','Deletes hero','Adds the armor key with value 3'],2,'Assignment to a new dictionary key adds it.');
lesson('get','Read a key that might be missing','Using square brackets for a missing dictionary key raises an error. get() can provide a fallback instead.','dictionary.get(key, default) returns the stored value when present, or the default when missing.', 'hero = {"hp": 50}\nprint(hero.get("mana", 0))\nprint(hero.get("hp", 0))', ['There is no mana key, so get returns the fallback 0.','hp exists, so get returns 50 instead of the fallback.'], 'What is {"hp": 10}.get("mana", 5)?', ['10','5','An error'],1,'mana is missing, so get uses the supplied default 5.');
lesson('dictvalues','Collect values from a dictionary','A dictionary stores both keys and values. .values() gives its values so you can loop through or add them.','len(dictionary) counts keys. sum(dictionary.values()) adds numeric values.', 'loot = {"coins": 4, "gems": 3}\nprint(len(loot))\nprint(sum(loot.values()))', ['There are two keys: coins and gems. len is 2.','The values are 4 and 3. Their sum is 7.'], 'What does .values() provide?', ['The dictionary\'s stored values','Only its keys','Only the first value'],0,'values() supplies the values associated with the keys.');
lesson('try','Recover from a problem','An exception is Python reporting that an operation could not finish. try/except lets you recover from a specific problem.','Put risky code in try. Put the fallback in except with the exception type you expect. Both blocks use colons and indentation.', 'text = "oops"\ntry:\n    number = int(text)\nexcept ValueError:\n    number = 0\nprint(number)', ['int tries to convert oops into an integer. That cannot work, so it raises ValueError.','The matching except stores 0 as a fallback.','Print 0. Try text = "8" to take the successful path.'], 'What should except ValueError handle here?', ['Any successful calculation','Text that int cannot convert','An empty backpack'],1,'An invalid integer string causes ValueError, so that except block can recover.');
lesson('exceptions','Match the error to the rescue','Different problems have different exception names. Catch the one your operation can produce.','ZeroDivisionError: division by zero. IndexError: missing list position. KeyError: missing dictionary key. TypeError: incompatible types.', 'values = [4, 7]\ntry:\n    item = values[9]\nexcept IndexError:\n    item = None\nprint(item)', ['A two-item list has indexes 0 and 1. Index 9 is absent.','Python raises IndexError. The matching except stores None, meaning no value.','Print None instead of stopping the program.'], 'Which error comes from 10 / 0?', ['KeyError','ZeroDivisionError','IndexError'],1,'Dividing by zero raises ZeroDivisionError.');
lesson('cleanup','A success path and a cleanup path','try can also have else and finally blocks. else runs only when try succeeds. finally runs after success or an exception.','Use else for work that belongs to success, and finally for cleanup needed either way.', 'try:\n    number = int("6")\nexcept ValueError:\n    print("bad input")\nelse:\n    print(number)\nfinally:\n    print("finished")', ['The conversion succeeds, so skip except.','else prints 6.','finally always prints finished. Try changing "6" to "bad".'], 'When does finally run?', ['Only when there is an error','Only on success','After either success or an exception'],2,'finally is the cleanup path for either outcome.');
lesson('raise','Report an invalid value','You can raise an exception when an input breaks your rules. This lets the caller decide how to recover.','Use raise ValueError("message") for a value that your function does not accept.', 'def require_positive(n):\n    if n <= 0:\n        raise ValueError("Must be positive")\n    return n\ntry:\n    print(require_positive(-2))\nexcept ValueError:\n    print("Choose a positive number")', ['The function sees that -2 is not positive and raises ValueError.','It does not reach return.','The caller catches the error and prints a helpful instruction.'], 'What does raise ValueError do?', ['Returns zero','Reports an error to the caller','Ignores the input'],1,'raise signals an exception. A matching try/except can recover from it.');
lesson('class','Make a blueprint for heroes','A class is a blueprint for objects. An object bundles its own data and actions. Two heroes can use the same blueprint but have different HP.','class Name: starts a blueprint. __init__ runs when an object is created. self refers to that particular object.', 'class Hero:\n    def __init__(self, hp):\n        self.hp = hp\na = Hero(30)\nb = Hero(50)\nprint(a.hp)\nprint(b.hp)', ['Define a Hero blueprint with a starting hp input.','Create a with 30 HP and b with 50 HP. self.hp stores each object\'s own value.','The two prints show 30 and 50.'], 'Do a and b share the same self.hp value?', ['Yes, always','No, each object has its own','Only if you print it'],1,'Instance attributes belong to each object individually.');
lesson('method','Teach an object an action','A method is a function defined inside a class. It can read or change that object\'s attributes through self.','Put self first in a method definition. Call object.method(arguments); Python supplies self automatically.', 'class Hero:\n    def __init__(self, hp):\n        self.hp = hp\n    def heal(self, amount):\n        self.hp += amount\nh = Hero(20)\nh.heal(5)\nprint(h.hp)', ['Create h with hp 20.','h.heal(5) receives h as self and 5 as amount.','Increase self.hp to 25 and print it.'], 'How do you call h\'s heal method with 3?', ['h.heal(3)','heal(self, 3)','h = heal(3)'],0,'The object comes before the dot. self is supplied automatically.');
lesson('classattr','Blueprint data and object data','An attribute defined directly in the class belongs to the blueprint. An attribute assigned through self belongs to an instance.','Read a class attribute with ClassName.attribute. Read an instance attribute with object.attribute.', 'class Hero:\n    species = "human"\n    def __init__(self, name="Nova"):\n        self.name = name\nprint(Hero.species)\nprint(Hero().name)', ['species is defined on the Hero class.','__init__ gives each object a name; the default is Nova.','Print human from the class and Nova from a new object.'], 'Where is species defined here?', ['On the Hero class','Only inside print','Inside a list'],0,'species is class data because it is assigned directly in the class body.');
lesson('combine','Combine your moves','A real program combines smaller ideas. Plan the input, the steps, and the result before writing code.','A function can loop through a collection, make decisions, and return a result. Break a big task into small moves.', 'def count_ready(hps):\n    total = 0\n    for hp in hps:\n        if hp > 0:\n            total += 1\n    return total\nprint(count_ready([5, 0, 8]))', ['The function receives a list of HP values.','Visit each value and count it only if it is positive.','Return 2, because two heroes are ready.'], 'What should you do first when a task combines several ideas?', ['Guess a giant line of code','Plan inputs, steps, and result','Skip all the earlier lessons'],1,'A small plan helps you combine familiar pieces without getting lost.');
const lessonRoutes=[
 ['assign','update','strings','assign','aug','strings','division','add','division','boolean','join','aug'],
 ['if','else','if','compare','compare','compare','else','logic','logic','elif','logic','logic'],
 ['list','index','index','list','append','index','listchange','slice','listchange','membership','sum','index'],
 ['for','range','range','range','accumulate','while','while','loopcontrol','loopcontrol','filter','range','for'],
 ['function','parameters','return','function','parameters','nested','compare','defaults','defaults','scope','compare','sum'],
 ['dict','dict','dictchange','dict','get','dictchange','membership','get','dictvalues','dictchange','dictvalues','accumulate'],
 ['try','try','exceptions','cleanup','exceptions','cleanup','try','exceptions','exceptions','exceptions','raise','cleanup'],
 ['class','class','class','class','method','method','method','method','method','classattr','method','defaults'],
 ['combine','clamp','clamp','accumulate','filter','dictvalues','clamp','clamp','try','dictchange','accumulate','finale']
];
const finaleStarter=`# Build the hero's blueprint.
class Hero:
    def __init__(self, name, hp):
        self.name = name
        self.hp = hp

    def take_hit(self, damage):
        # TODO: subtract damage from self.hp, never below 0
        pass

# Turn damage text into a safe number.
def parse_damage(text):
    # TODO: return int(text), never below 0
    # TODO: catch ValueError and return 0 for invalid text
    pass

# Use your hero, a dragon dictionary, and a list of attacks.
def fight(hero, dragon, hits):
    # TODO: loop through hits
    # Stop if your hero has no HP.
    # Parse each hit and subtract it from dragon["hp"], never below 0.
    # Return "victory" as soon as the dragon reaches 0 HP.
    # Otherwise let the dragon hit your hero using dragon["attack"].
    # After the loop, return "victory" if the dragon is defeated, else "retry".
    pass

hero = Hero("Mira", 100)
dragon = {"hp": 30, "attack": 5}
attacks = ["10", "oops", "20"]
print(fight(hero, dragon, attacks))`;
const finaleVerify=`parse_damage("7") == 7 and parse_damage("oops") == 0 and parse_damage("-4") == 0 and (lambda h: (h.take_hit(8), h.name == "Test", h.hp == 12, h.take_hit(99), h.hp == 0)[1:3] == (True, True) and h.hp == 0)(Hero("Test", 20)) and (lambda h,d: fight(h,d,["5","bad","9"]) == "victory" and d["hp"] == 0 and h.hp == 14)(Hero("Test",20),{"hp":14,"attack":3}) and (lambda h,d: fight(h,d,["2"]) == "retry" and d["hp"] == 8 and h.hp == 18)(Hero("Test",20),{"hp":10,"attack":2}) and (lambda h,d: fight(h,d,["1","99"]) == "retry" and d["hp"] == 9 and h.hp == 0)(Hero("Test",2),{"hp":10,"attack":3}) and (lambda h,d: fight(h,d,[]) == "victory" and h.hp == 20)(Hero("Test",20),{"hp":0,"attack":3})`;
lesson('finale','The final boss: build a battle engine','The dragon guards the whole kingdom. Your code will control a real battle: a hero object, a dragon record, and a sequence of attacks. Each piece uses a skill you have already learned.','Plan three pieces: a Hero class, a safe damage parser, and a fight function. Keep each piece small. The practice example below shows how a loop and a decision work together.', 'def raid(hp, hits):\n    for hit in hits:\n        hp = max(0, hp - hit)\n        if hp == 0:\n            return "cleared"\n    return "try again"\nprint(raid(9, [2, 3, 4]))', ['Variables store hp; the list stores each attack. A function receives them.','The loop subtracts one hit at a time: 9 → 7 → 4 → 0. max prevents negative HP.','The if detects zero. return sends cleared to print. Your boss task adds a class, dictionary, and error handling.'], 'What should fight do as soon as the dragon reaches 0 HP?', ['Return "victory" before the dragon attacks again','Keep taking dragon attacks','Reset all the variables'],0,'Check the dragon after your hit. Returning victory immediately prevents one extra enemy attack.');
let lessonPhase='learn',lessonStep=0,lessonChoicePassed=false,lessonViewKey=null,lessonBusy=false,forcedLesson=false;
function lessonFor(p){return lessons[lessonRoutes[p.m][p.c]];}
function lessonComplete(p){return reviewMode||state.completed[keyOf(p.m,p.c)]||!!state.lessonDone?.[keyOf(p.m,p.c)];}
function learningActive(){return !reviewMode&&(forcedLesson||!lessonComplete(position()));}
function installFinalBoss(){
  missions[8].challenges[11]={type:'Build',prompt:'Final boss: write the battle engine.\n\n1. Hero(name, hp) stores self.name and self.hp. take_hit(damage) subtracts damage without letting HP fall below 0.\n2. parse_damage(text) returns a nonnegative integer. Invalid integer text returns 0.\n3. fight(hero, dragon, hits) visits attack strings in order. Stop if the hero has no HP. Subtract each parsed hit from dragon["hp"] (minimum 0). Return "victory" immediately when dragon HP is 0; otherwise apply dragon["attack"] to the hero. After the loop, return "victory" if the dragon is defeated or "retry" if it survives.\n4. Run the supplied Mira battle and print victory.',clue:'Solve one piece at a time. Hero.take_hit uses max. parse_damage uses try/except ValueError. fight uses for, if, dictionary keys, and return.',placeholder:'Build your battle engine here',why:'You are combining all eight Python regions into a working game program.',reward:500,test:a=>!!a.trim(),success:'You built a working battle engine! Your code handled invalid attacks, victory, defeat, and HP limits.',output:'victory',runtime:{verify:finaleVerify,expectedStdout:'victory'},starter:finaleStarter};
  if(state.capstoneVersion!==1){if(state.completed['8:11']){delete state.completed['8:11'];if(state.lessonDone)delete state.lessonDone['8:11'];if(state.rewardNotices)delete state.rewardNotices[8];}state.capstoneVersion=1;save();}
}
function initTeaching(){
  installFinalBoss();
  if(!state.lessonDone||typeof state.lessonDone!=='object')state.lessonDone={};
  el('lessonNextStep').onclick=()=>{const lesson=lessonFor(position());lessonStep=Math.min(lesson.steps.length-1,lessonStep+1);renderLessonTrace();};
  el('lessonResetSteps').onclick=()=>{lessonStep=0;renderLessonTrace();};
  el('lessonTryBtn').onclick=()=>{lessonPhase='try';renderTeaching();el('lessonCodeInput').focus();};
  el('lessonBackBtn').onclick=()=>{lessonPhase='learn';renderTeaching();};
  el('lessonRunDemo').onclick=runLessonDemo;
  el('lessonResetDemo').onclick=()=>{if(!lessonBusy){el('lessonCodeInput').value=lessonFor(position()).code;el('lessonDemoOutput').textContent='Example restored. Try changing a value and run it.';}};
  el('lessonEnterBattle').onclick=()=>{if(!lessonChoicePassed||lessonBusy)return;state.lessonDone[keyOf(position().m,position().c)]=true;forcedLesson=false;save();renderBattle();renderTeaching();el('answerInput').focus({preventScroll:true});el('battleWorkspace').scrollIntoView({block:'start'});};
  el('revisitLesson').onclick=()=>{if(el('runBtn').disabled||lessonBusy)return;forcedLesson=true;lessonPhase='learn';lessonStep=0;lessonChoicePassed=false;renderTeaching();el('lessonTitle').scrollIntoView({block:'start'});};
  el('battleStarter').onclick=()=>{if(el('runBtn').disabled||lessonBusy)return;const starter=current().starter;if(starter&&(!el('answerInput').value.trim()||confirm('Replace your current code with the starter?'))){el('answerInput').value=starter;el('answerInput').focus();}};
  el('mistakeCoach').onclick=()=>{const ch=current();el('coachAdvice').hidden=false;el('coachAdvice').textContent=ch.clue+' '+lessonFor(position()).idea;};
  el('lessonCodeInput').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const t=e.target,s=t.selectionStart,n=t.selectionEnd;t.value=t.value.slice(0,s)+'    '+t.value.slice(n);t.selectionStart=t.selectionEnd=s+4;}});
}
function renderTeaching(){
  const p=position(),key=keyOf(p.m,p.c),lesson=lessonFor(p);
  if(lessonViewKey!==key){lessonViewKey=key;lessonPhase='learn';lessonStep=0;lessonChoicePassed=false;forcedLesson=false;}
  const show=learningActive();
  el('lessonPanel').hidden=!show;el('battleWorkspace').hidden=show;el('battleDock').hidden=show;el('celebrationLayer').hidden=show;
  document.querySelector('.main').classList.toggle('learningMode',show);
  el('missionMode').textContent=reviewMode?'REVIEW ARENA':show?'LEARN A NEW MOVE':'PUT YOUR SKILL TO WORK';
  el('welcomeStory').hidden=!(p.m===0&&p.c===0&&!state.completed['0:0']);
  el('lessonTitle').textContent=lesson.title;el('lessonIdea').textContent=lesson.idea;el('lessonUse').textContent=lesson.use;
  el('lessonReadPane').hidden=lessonPhase!=='learn';el('lessonTryPane').hidden=lessonPhase!=='try';
  el('lessonLearnTab').classList.toggle('active',lessonPhase==='learn');el('lessonTryTab').classList.toggle('active',lessonPhase==='try');
  el('lessonProgress').textContent='Encounter '+(p.c+1)+' / 12 · '+(p.m===8&&p.c===11?'Final boss preparation':'Safe training: mistakes cost no HP');
  renderLessonTrace();
  el('lessonCodeInput').value=lesson.code;el('lessonDemoOutput').textContent='This is a safe playground. Change a value and run your experiment.';
  el('lessonQuestion').textContent=lesson.question;el('lessonOptions').replaceChildren();
  lesson.options.forEach((text,i)=>{const button=document.createElement('button');button.className='lessonOption';button.textContent=text;button.onclick=()=>{lessonChoicePassed=i===lesson.answer;el('lessonCheckFeedback').textContent=lessonChoicePassed?'You got it! '+lesson.explanation:'Let’s work it out. '+lesson.explanation+' Try another choice.';el('lessonCheckFeedback').className=lessonChoicePassed?'lessonCheckFeedback good':'lessonCheckFeedback';el('lessonEnterBattle').disabled=!lessonChoicePassed;button.classList.add(lessonChoicePassed?'correctChoice':'wrongChoice');};el('lessonOptions').append(button);});
  el('lessonCheckFeedback').textContent=lessonChoicePassed?'Ready for battle. You can still experiment with the example.':'Choose an answer. You can try as often as you like.';
  el('lessonEnterBattle').disabled=!lessonChoicePassed||lessonBusy;
  el('revisitLesson').hidden=reviewMode;el('battleStarter').hidden=!current().starter;
  el('battleContext').hidden=!current().runtime?.setup;el('battleContextCode').textContent=current().runtime?.setup||'';
  el('coachAdvice').hidden=true;el('mistakeCoach').hidden=true;
  el('bossPlan').hidden=!(p.m===8&&p.c===11);
  renderCodeWorld();renderVillageShell();
}
function renderLessonTrace(){
  const lesson=lessonFor(position());el('lessonExample').textContent=lesson.code;
  el('lessonTrace').textContent=lesson.steps[lessonStep];el('lessonStepCount').textContent='Step '+(lessonStep+1)+' / '+lesson.steps.length;
  el('lessonNextStep').disabled=lessonStep>=lesson.steps.length-1;
}
async function runLessonDemo(){
  if(lessonBusy||el('runBtn').disabled)return;
  const code=el('lessonCodeInput').value;if(!code.trim()){el('lessonDemoOutput').textContent='Write some code first, or restore the example.';return;}
  lessonBusy=true;el('lessonRunDemo').disabled=true;el('lessonRunDemo').textContent='Running Python…';el('lessonEnterBattle').disabled=true;
  try{const result=await executePython(code);renderCodeWorld(result);el('lessonDemoOutput').textContent=result.ok?(result.stdout.trim()||'Your program ran. Add print(...) to show a value.'):'No HP lost. '+friendlyError(result.stderr)+'\n\n'+result.stderr;}
  catch(error){renderCodeWorld({ok:false});el('lessonDemoOutput').textContent='No HP lost. '+error.message;}
  finally{lessonBusy=false;el('lessonRunDemo').disabled=false;el('lessonRunDemo').textContent='Run experiment';el('lessonEnterBattle').disabled=!lessonChoicePassed;}
}
function friendlyError(stderr){
  if(/SyntaxError/.test(stderr))return 'Python could not read a line. Check matching quotes and parentheses, and the colon after if, for, def, or class.';
  if(/IndentationError|TabError/.test(stderr))return 'Check indentation: instructions inside a block need four spaces. Keep lines in the same block aligned.';
  if(/NameError/.test(stderr))return 'Python does not know that name yet. Check its spelling and define it before using it. Text needs quotes.';
  if(/TypeError/.test(stderr))return 'These value types do not fit that operation. Check whether you are using text, a number, or a collection.';
  if(/IndexError/.test(stderr))return 'That list position does not exist. Count from 0 and stay inside the list.';
  if(/KeyError/.test(stderr))return 'That dictionary key is missing. Check the key spelling or use get with a default.';
  if(/ValueError/.test(stderr))return 'That value could not be used as requested. Check conversions such as int(text).';
  return 'The program stopped. Read the last line of the message and compare your code with the example.';
}
function teachingFeedback(p,result){
  el('mistakeCoach').hidden=false;el('coachAdvice').hidden=false;
  const concept=lessonFor(p),ch=missions[p.m].challenges[p.c];
  el('coachAdvice').textContent=result?.stderr?friendlyError(result.stderr):ch.type==='Predict'?'Trace one line at a time. '+ch.clue:'Your result does not yet meet the goal. '+ch.clue;
  if((state.attempts[keyOf(p.m,p.c)]||0)>=3)el('coachAdvice').textContent+=' You can revisit the lesson above for another safe example.';
}
